---
title: "HW 9"
author: "Tracie-Lynn Lamoreux"
date: "2023-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```


```{r, include = FALSE}
av <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)

my_cols<- c("Death1","Death2","Death3","Death4","Death5")
deaths <- av %>%
  pivot_longer(cols = my_cols, names_to = "Time", values_to = "Death") %>%
  mutate(Time = parse_number(Time),
         Death = ifelse(Death == "","", ifelse(Death == "YES", "yes", "no")))
my_cols_return<- c("Return1","Return2","Return3","Return4","Return5")
returns <- av %>%
  pivot_longer(cols = my_cols_return, names_to = "Time", values_to = "Return") %>%
  mutate(Time = parse_number(Time),
         Return = ifelse(Return == "","", ifelse(Return == "YES", "yes", "no")))
```

Tracie-Lynn Fact Check:</br>
"and on 57 occasions the individual made a comeback." 
```{r, include = FALSE}
new_return<- returns %>% filter(Return == "yes")
unique<- unique(new_return$URL)
numberofuniquereturns<- length(unique)
```
This statement is FALSE. The number of returns for a unique character is = to `r numberofuniquereturns`.

